api = "0.9"

[buildpack]
id = "edume/heroku-buildpack-multi-procfile"
version = "1.0.0"
name = "Heroku Buildpack Multi-Procfile"
homepage = "https://github.com/edume/heroku-buildpack-multi-procfile"

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-22"
